const Types = {
  LOGIN_FACULTY: "LOGIN_FACULTY",
  LOGIN_STUDENT: "LOGIN_STUDENT",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  POST_EXAM_FORM_SUCESS: "POST_EXAM_FORM_SUCESS",
  POST_EXAM_FORM_FAIL: "POST_EXAM_FORM_FAIL",
  GET_HALL_TICKET_STATUS: "GET_HALL_TICKET_STATUS",
  SET_USER: "SET_USER",

  APPLY_FILTER: "APPLY_FILTER",

  GET_ALL_STUDENTS: "GET_ALL_STUDENTS",
  GET_ALL_STUDENTS_BY_DEPARTMENT: "GET_ALL_STUDENTS_BY_DEPT", // No route

  VERIFY_ALL: "VERIFY_ALL",
  VERIFY_BY_ROLL_NO: "VERIFY_BY_ROLL_NO",

  GENERATE_HALL_TICKET_REQUEST: "GENERATE_HALL_TICKET_REQUEST", // Loading
  GENERATE_HALL_TICKET_SUCESS: "GENERATE_HALL_TICKET_SUCESS",
  GENERATE_HALL_TICKET_FAIL: "GENERATE_HALL_TICKET_FAIL",
};

export default Types;
